### ISSUE TITLE
Also highlight marked pairs in "ordered table" view

### ISSUE THREAD

**Issue by Nullmann** [Nullmann/moodle-plagiarism_programming#19]
Grouping students highlights selected pairs in the ordered view after they are marked as suspicious or normal:

![grafik](https://user-images.githubusercontent.com/15816473/57931197-37faa700-78b8-11e9-8bf2-a3dafc459d27.png)

But this is not the case when you select a specific student:

![grafik](https://user-images.githubusercontent.com/15816473/57931241-4a74e080-78b8-11e9-9c48-fcdb7a4ab6bb.png)

**Comment by Nullmann** [comment]
Question: Should this also be the case when students can see the results? They can only see the table view (the second picture), not the matrix view.

**Comment by roessling** [comment]
Can students actually see the names of the authors of "similar" solutions (as in the second picture)? That might raise privacy (and other) concerns.
I would not mind if students can see that their submission was flagged as "suspicious" or "OK", if that was the main underlying question...

**Comment by Nullmann** [comment]
No, they cannot see the other students names anymore, this was an old screenshot. With the if-statement [here](https://github.com/Nullmann/moodle-plagiarism_programming/commit/f15202cf8afb1682b6c72e636af1514f9d660207#diff-19db38d54cfae2071270282ca47a812aR166), students are currently not able to see the markings.

I think the easiest solution is to add an additional setting to the assignment settings in which teacher can decide if the students can see these markings. Reopening this issue for that.
