### ISSUE TITLE
Integrate Moodle Privacy API

### ISSUE THREAD

**Issue by Nullmann** [Nullmann/moodle-plagiarism_programming#27]
As this tool saves users'personal data, the API point should be implemented:
https://docs.moodle.org/dev/Privacy_API

Especially local files and the table "plagiarism_programming_reslt" need to be adressed.

**Comment by Nullmann** [comment]
Testing is made easier with these scripts:
https://gist.github.com/luukverhoeven/c53e5585a9d059cf61537f6d7f37863a
https://docs.moodle.org/dev/Privacy_API/Utilities

**Comment by Nullmann** [comment]
There is a problem when we want to delete a specific user: As we store our results on a per-comparison-basis, [each row contains 2 different user ids](https://github.com/Nullmann/moodle-plagiarism_programming/blob/master/db/install.xml#L80). Like this, deleting one userid might influence the max similarity of another user. 

An alternative could be to switch the userid with the id of the guest user. But this would result in duplicate userid's and confusion for teachers.

**Comment by roessling** [comment]
Is it possible to flag a user ID as a "former user" (if the user has been deleted), so that the similarity stays as it was (until a new scan is done)?

**Comment by Nullmann** [comment]
When a user requests the deletion of his/her data (which has to be approved by the privacy officer), this seems to be equivalent to manually deleting the user. As such, no standard Moodle functions will return this student anymore.
